#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 13 18:58:18 2018

@author: humza
"""

stickers = {'2 clubs': "CAADBAADMwADjkyzC3xhbwJiwFvjAg",
'2 Diamonds': "CAADBAADNAADjkyzC16Y7FRChKm4Ag",
'2 Hearts': "CAADBAADNQADjkyzCysk3LXxn5cTAg",
'2 Spades': "CAADBAADNgADjkyzC90CX-KkFFwfAg",
'3 Clubs': "CAADBAADNwADjkyzCy8hnETSNqLtAg",
'3 Diamonds': "CAADBAADOAADjkyzC0-aw8kHmw30Ag",
'3 Hearts': "CAADBAADOQADjkyzC_fH8Vq5kakXAg",
'3 Spades': "CAADBAADOgADjkyzC7BDgk32K21RAg",
'4 Clubs': "CAADBAADOwADjkyzC4w0lmJML280Ag",
'4 Diamonds': "CAADBAADPAADjkyzCxc2sK40m9DNAg",
'4 Hearts': "CAADBAADPQADjkyzC8sYQO08JGOyAg",
'4 Spades': "CAADBAADPgADjkyzC3VyJ82ckS_mAg",
'5 Clubs': "CAADBAADPwADjkyzC8MN-6CDL8QHAg",
'5 Diamonds': "CAADBAADQAADjkyzC0lGVhn-WTZ-Ag",
'5 Hearts': "CAADBAADQQADjkyzC-7FvjU3QGhtAg",
'5 Spades': "CAADBAADQgADjkyzC5wk5qi1mXPJAg",
'6 Clubs': "CAADBAADQwADjkyzC7aXMqR-PUdLAg",
'6 Diamonds': "CAADBAADRAADjkyzC5U6ayzrXUgqAg",
'6 Hearts': "CAADBAADRQADjkyzC0FRrDsEPVAJAg",
'6 Spades': "CAADBAADRgADjkyzC-Eghihr9wylAg",
'7 Clubs': "CAADBAADRwADjkyzC_1Qwkk2usAzAg",
'7 Diamonds': "CAADBAADSAADjkyzC3h4ZvWP3jJhAg",
'7 Hearts': "CAADBAADSQADjkyzC9wcqf4Y5BygAg",
'7 Spades': "CAADBAADSgADjkyzC_motUCLfmsUAg",
'8 Clubs': "CAADBAADSwADjkyzC2u12qY5hM5nAg",
'8 Diamonds': "CAADBAADTAADjkyzC_3pah-hoXkcAg",
'8 Hearts': "CAADBAADTQADjkyzCziLfN90KXkmAg",
'8 Spades': "CAADBAADTgADjkyzCx7i9a0YRCsBAg",
'9 Clubs': "CAADBAADTwADjkyzC_bg6NqJX7udAg",
'9 Diamonds': "CAADBAADUAADjkyzC9AYQix3HTiZAg",
'9 Hearts': "CAADBAADUQADjkyzC0tHv5aC8vpiAg",
'9 Spades': "CAADBAADUgADjkyzC6-u5XxUE0c7Ag",
'10 Clubs': "CAADBAADUwADjkyzCx3Q9I5EchgzAg",
'10 Diamonds': "CAADBAADVAADjkyzC5hgBfCNpRvEAg",
'10 Hearts': "CAADBAADVQADjkyzC1w6NfNnmJC4Ag",
'10 Spades': "CAADBAADVgADjkyzC6QZ8-DIX5g8Ag",
'A Clubs': "CAADBAADVwADjkyzC_YwFbifb_QuAg",
'A Diamonds': "CAADBAADWAADjkyzC2bpEj-eoGOQAg",
'A Hearts': "CAADBAADWQADjkyzC30WThf2NGl0Ag",
'A Spades': "CAADBAADWgADjkyzC2tfF_aZT1feAg",
'J Clubs': "CAADBAADWwADjkyzC7M-fflTB6GiAg",
'J Diamonds': "CAADBAADXAADjkyzC3pL9L4ReCHXAg",
'J Hearts': "CAADBAADXQADjkyzC-5oVsToSVJjAg",
'J Spades': "CAADBAADXwADjkyzCwW07g_8YxlJAg",
'K Clubs': "CAADBAADXgADjkyzC_cVhYW1BgABQwI",
'K Diamonds': "CAADBAADYAADjkyzCxJjUcagl3QyAg",
'K Hearts': "CAADBAADYQADjkyzCzZKmjC_WqcJAg",
'K Spades': "CAADBAADYgADjkyzCytcbBcliSSbAg",
'Q Clubs': "CAADBAADYwADjkyzC3VxhTNIFussAg",
'Q Diamonds': "CAADBAADZAADjkyzC2BRX-QKkSdJAg",
'Q Hearts': "CAADBAADZQADjkyzC2r9XJ1NVHckAg",
'Q Spades': "CAADBAADZgADjkyzCy5Xy81sFf_lAg"}

